version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: glamcheck
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
